<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.7">
  <POU Name="BFT_TO_MS" Id="{7c615141-11d2-4bde-9bd5-0b340e833e37}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION BFT_TO_MS : REAL
VAR_INPUT
	BFT : INT;
END_VAR


(*
version 1.0	12. jun 2008
programmer 	hugo
tested by		oscdat

this function converts wind speed from beaufort to m/s
*)]]></Declaration>
    <Implementation>
      <ST><![CDATA[BFT_TO_MS := EXPT(BFT, 1.5) * 0.836;


(* revision history
hm	12. 6. 2008		rev 1.0
	original version

*)]]></ST>
    </Implementation>
    <LineIds Name="BFT_TO_MS">
      <LineId Id="13" Count="7" />
    </LineIds>
  </POU>
</TcPlcObject>