<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.7">
  <POU Name="C_TO_K" Id="{15ef520f-bc8b-4dd5-8a81-3b8d7a842450}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION C_TO_K : REAL
VAR_INPUT
	Celsius : REAL;
END_VAR


(*
version 1.1	19. aug 2009
programmer 	hugo
tested by		tobias

this function converts celsius to kelvin
*)]]></Declaration>
    <Implementation>
      <ST><![CDATA[C_TO_K := Celsius - phys.T0;

(* revision history

hm	4. aug 2006	rev 1.0
	original version

hm	19. aug 2009	rev 1.1
	fixed calculation error

*)
]]></ST>
    </Implementation>
    <LineIds Name="C_TO_K">
      <LineId Id="13" Count="11" />
    </LineIds>
  </POU>
</TcPlcObject>