<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.7">
  <POU Name="MINUTE" Id="{e7ac8a50-59c3-4a45-aa60-043907af03ec}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION MINUTE : INT
VAR_INPUT
	itod : TOD;
END_VAR


(*
version 1.1	2 oct 2006
programmer 	hugo
tested by	tobias

extracts the minutes out of TOD truncating the seconds 

*)  ]]></Declaration>
    <Implementation>
      <ST><![CDATA[MINUTE := DWORD_TO_INT(TOD_TO_DWORD(itod) / 60000 - TOD_TO_DWORD(itod) / 3600000 * 60);


(* change history

2.10.2006 changes name of input to itod

*)]]></ST>
    </Implementation>
    <LineIds Name="MINUTE">
      <LineId Id="14" Count="7" />
    </LineIds>
  </POU>
</TcPlcObject>