<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.7">
  <POU Name="CPOW" Id="{2138ed19-247c-4c94-b200-cb6901f91309}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION CPOW : complex
VAR_INPUT
	X : complex;
	Y : Complex;
END_VAR


(*
version 1.0	21 feb 2008
programmer 	hugo
tested by	oscat

this function calculates the complex power function x to the power of y

*)]]></Declaration>
    <Implementation>
      <ST><![CDATA[CPOW := CEXP(CMUL(Y,CLOG(X)));


(* revision history
hm	21. feb 2008	rev 1.0
	original version

*)]]></ST>
    </Implementation>
    <LineIds Name="CPOW">
      <LineId Id="15" Count="7" />
    </LineIds>
  </POU>
</TcPlcObject>