<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.7">
  <POU Name="MAIN" Id="{6de127fa-b6f4-4656-b169-9e870eadfc1d}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR

	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[loopCounter := loopCounter + 1;

PRG_ReadModbusSensorData();

(* PRG_HandleUserInputs(); *)

PRG_UpdateMotor();

PRG_UpdateTemperatureControl();

PRG_UpdatePressureSensor();
PRG_UpdateFlowRateSensor();
PRG_UpdatePhControl();
PRG_UpdateGasSupply();
PRG_UpdateRoomTempRh();
PRG_GasAnalysis();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="43" Count="1" />
      <LineId Id="2" Count="0" />
      <LineId Id="34" Count="0" />
      <LineId Id="33" Count="0" />
      <LineId Id="35" Count="0" />
      <LineId Id="32" Count="0" />
      <LineId Id="37" Count="0" />
      <LineId Id="36" Count="0" />
      <LineId Id="51" Count="0" />
      <LineId Id="50" Count="0" />
      <LineId Id="52" Count="1" />
      <LineId Id="59" Count="0" />
      <LineId Id="65" Count="0" />
      <LineId Id="8" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>