<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.7">
  <POU Name="MS_TO_KMH" Id="{1add4aab-ade8-4b49-8bbc-2c30303d399f}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION MS_TO_KMH : REAL
VAR_INPUT
	ms : REAL;
END_VAR


(*
version 1.0	4 Feb 2007
programmer 	hugo
tested by		tobias

this function converts velocities from Meters / Second to Kilometers / hour.

*)]]></Declaration>
    <Implementation>
      <ST><![CDATA[MS_TO_KMH := ms * 3.6;

]]></ST>
    </Implementation>
    <LineIds Name="MS_TO_KMH">
      <LineId Id="14" Count="2" />
    </LineIds>
  </POU>
</TcPlcObject>